CREATE TABLE IF NOT EXISTS courses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    credits REAL NOT NULL,
    category TEXT NOT NULL,
    status TEXT NOT NULL,
    score REAL,
    grade TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
